"""
Docstring for blockchain.src.main
as i am making it for govemment we need few fields:
  sender
  reciever
  time_stamp
  amount
  prev_hash
  hash (current hash)
  agreement
"""
import datetime
from util.hash import generate_hash
from int2word import generate_word

class Block:
  def __init__(self, sender, receiver, time_stamp, amount, prev_hash, agreement):
    self.sender = sender
    self.receiver = receiver
    self.time_stamp = time_stamp
    self.amount = amount
    self.prev_hash = prev_hash
    self.agreement = agreement
    self.current_hash = self.calcualte_hash()

  def calcualte_hash(self):
    return generate_hash(f'{self.sender}-{self.receiver}-{self.agreement}-{self.amount}-{self.time_stamp}-{self.prev_hash}')
    
class BlockChain:
  def __init__(self):
    self.chain = []

  def create_genisis_block(self):
    """
    this function creates the genisis block. The genisis block is the 1st block in a blockchain and has some predefault features like:
      1. initial message
      2. sender = system
      3. reciever = None
      4. transaction = None

    the current_hash is generated by hashing a string 
    """
    date = datetime.datetime.now()
    agreement = f"This block was created on: {date}"
    block = Block(time_stamp=date, agreement=agreement, prev_hash=None, sender="System", receiver=None, amount=None)

    self.chain.append(block)
  
  def add_block(self, sender, reciever, amount):
    date = datetime.datetime.now()
    prev_hash = self.chain[len(self.chain)-1].current_hash
    amount_in_words = generate_word(amount)
    agreement = f"{sender} sends ₹{amount}-/ i.e {amount_in_words.capitalize()}, to {reciever} on {date}"
    new_block = Block(sender=sender, receiver=reciever, time_stamp=date,amount=amount,prev_hash=prev_hash,agreement=agreement)
    # print(current_hash)
    self.chain.append(new_block)
  
  def print_chain(self):
    for block in self.chain:
      print("Time stamp:",block.time_stamp)
      print("Agreement:",block.agreement)
      print("Sender:",block.sender)
      print("Reciever:",block.receiver)
      print("Previous hash:",block.prev_hash)
      print("Current hash:",block.current_hash)
      print("-------")
  
blockChain = BlockChain()
blockChain.create_genisis_block()
blockChain.add_block("Saumya","Roshan",1322)
blockChain.add_block("Susanti","Roshan",100)
blockChain.add_block("Roshan","Bhumika",7545)
blockChain.add_block("Bhumika","Saumya",18454)

blockChain.print_chain()